# Generated by Django 4.1.13 on 2024-04-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_player_lastpolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='winner',
            new_name='creator_profile_id',
        ),
    ]
