# Generated by Django 4.1.13 on 2024-04-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_rename_winner_game_creator_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='diplomacy_type',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='map_id',
            field=models.SmallIntegerField(null=True),
        ),
    ]
