# Generated by Django 4.1.13 on 2024-04-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_alter_game_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator_profile_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.IntegerField(null=True),
        ),
    ]
