# Generated by Django 4.1.13 on 2024-04-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_alter_game_creator_profile_id_alter_game_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='civ_id',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='player_position',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='rating',
            field=models.SmallIntegerField(),
        ),
    ]
