# Generated by Django 4.1.13 on 2024-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0008_alter_gameplayer_civ_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='rating',
            field=models.SmallIntegerField(null=True),
        ),
    ]
