# Generated by Django 4.1.13 on 2024-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0009_alter_gameplayer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='downloaded',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Completed'), (2, '404 Not Found'), (3, '429 Rate Limited'), (4, '403 Refused Request')], max_length=12),
        ),
    ]
