# Generated by Django 4.1.13 on 2024-04-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0011_alter_game_downloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayerMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('profile_id', models.IntegerField()),
                ('civ_id', models.SmallIntegerField(null=True)),
                ('player_position', models.SmallIntegerField(null=True)),
                ('rating', models.SmallIntegerField(null=True)),
                ('loom_timing', models.DurationField(null=True)),
                ('wheelbarrow_timing', models.DurationField(null=True)),
            ],
            options={
                'unique_together': {('game_id', 'profile_id')},
            },
        ),
    ]
