# Generated by Django 4.1.13 on 2024-04-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0012_gameplayermetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayermetadata',
            name='civ_id',
        ),
        migrations.RemoveField(
            model_name='gameplayermetadata',
            name='player_position',
        ),
        migrations.RemoveField(
            model_name='gameplayermetadata',
            name='rating',
        ),
    ]
