# Generated by Django 4.1.13 on 2024-04-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0013_remove_gameplayermetadata_civ_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayermetadata',
            name='metadata_version',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gamemetadata',
            name='metadata_version',
            field=models.IntegerField(),
        ),
    ]
