# Generated by Django 4.1.13 on 2024-04-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0014_gameplayermetadata_metadata_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemetadata',
            name='metadata_version',
        ),
        migrations.RemoveField(
            model_name='gameplayermetadata',
            name='metadata_version',
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='data_version',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='data_version',
            field=models.SmallIntegerField(null=True),
        ),
    ]
