# Generated by Django 4.1.13 on 2024-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0015_remove_gamemetadata_metadata_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='downloaded',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Completed'), (2, '404 Not Found'), (3, '429 Rate Limited'), (4, '403 Refused Request'), (5, 'other error'), (6, 'Runtime error')], max_length=12),
        ),
    ]
