# Generated by Django 4.1.13 on 2024-04-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0016_alter_game_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayermetadata',
            name='rating',
            field=models.SmallIntegerField(null=True),
        ),
    ]
