# Generated by Django 4.1.13 on 2024-05-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0017_gameplayermetadata_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayermetadata',
            name='bow_saw_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='castle_age_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='crop_rotation_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='double_bit_axe_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='feudal_age_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='gillnets_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='gold_mining_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='gold_shaft_mining_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='hand_cart_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='heavy_plow_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='herbal_medicine_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='horse_collar_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='imperial_age_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='stone_mining_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='stone_shaft_mining_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='town_watch_timing',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='two_man_saw_timing',
            field=models.DurationField(null=True),
        ),
    ]
