# Generated by Django 4.1.13 on 2024-05-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0018_gameplayermetadata_bow_saw_timing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayermetadata',
            name='civilization',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='eapm',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='prefer_random',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='gameplayermetadata',
            name='winner',
            field=models.BooleanField(null=True),
        ),
    ]
